[variables]
# On force PHP 8.3 pour satisfaire OpenSpout/Filament
NIXPACKS_PHP_VERSION = "8.3"
PHP_EXTENSIONS = "intl, zip, bcmath, gd, opcache, pdo_mysql"

[phases.setup]
# On installe les extensions pour la version 8.3
nixPkgs = ["...", "php83Extensions.intl", "php83Extensions.zip"]